@echo off
REM Generated by trunk tool 'checkov'
set PATH=C:\Users\yoshimori\AppData\Local\trunk\tools\checkov\3.1.67-ddf8b9a1ff025ff49fdd2926fa071d79/bin;C:\Users\yoshimori\AppData\Local\trunk\tools\checkov\3.1.67-ddf8b9a1ff025ff49fdd2926fa071d79/Scripts;C:\Users\yoshimori\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070/bin;C:\Users\yoshimori\AppData\Local\trunk\tools\python\3.10.8-2211cb108575de2785d77a26a1f8d070;C:\Users\yoshimori\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\yoshimori\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set VIRTUAL_ENV=C:\Users\yoshimori\AppData\Local\trunk\tools\checkov\3.1.67-ddf8b9a1ff025ff49fdd2926fa071d79
set HOME=%HOME%
if not defined HOME set HOME=
set PYTHONUTF8=1

start /w /b checkov %*
