@echo off
REM Generated by trunk tool 'osv-scanner'
set PATH=C:\Users\yoshimori\AppData\Local\trunk\tools\osv-scanner\1.6.1-071f4b0a58b229c7410194e22bb17ccd;C:\Users\yoshimori\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\yoshimori\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b osv-scanner %*
