@echo off
REM Generated by trunk tool 'prettier'
set PATH=C:\Users\yoshimori\AppData\Local\trunk\tools\prettier\3.2.4-2ed51cc921c759ecb4e52a2042753dfb/node_modules/.bin;C:\Users\yoshimori\AppData\Local\trunk\tools\node\18.12.1-ee91e409de31a08a96aaff7f742f83b4/bin;C:\Users\yoshimori\AppData\Local\trunk\tools\node\18.12.1-ee91e409de31a08a96aaff7f742f83b4;C:\Users\yoshimori\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\yoshimori\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set NODE_PATH=C:\Users\yoshimori\AppData\Local\trunk\tools\prettier\3.2.4-2ed51cc921c759ecb4e52a2042753dfb/node_modules
set HOME=%HOME%
if not defined HOME set HOME=

start /w /b prettier %*
