@echo off
REM Generated by trunk tool 'trufflehog'
set PATH=C:\Users\yoshimori\AppData\Local\trunk\tools\trufflehog\3.63.10-c7078ded9b6a9adc7b82858e747e4837;C:\Users\yoshimori\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\yoshimori\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b trufflehog %*
